### ISSUE TITLE
Fix `mix test` while in market_manager

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [Fl4m3Ph03n1x/market_manager#40]
When running `mix test` inside of market_manager I get the following error:

```
 mix test
warning: path "apps/.elixir_ls" is a directory but it has no mix.exs. Mix won't consider this directory as part of your umbrella application. Please add a "mix.exs" or set the ":apps" key in your umbrella configuration with all relevant apps names as atoms
warning: path "apps/.vscode" is a directory but it has no mix.exs. Mix won't consider this directory as part of your umbrella application. Please add a "mix.exs" or set the ":apps" key in your umbrella configuration with all relevant apps names as atoms
warning: Phoenix now requires you to explicitly list which engine to use
for Phoenix JSON encoding. We recommend everyone to upgrade to
Jason by setting in your config/config.exs:

    config :phoenix, :json_library, Jason

And then adding {:jason, "~> 1.0"} as a dependency.

If instead you would rather continue using Poison, then add to
your config/config.exs:

    config :phoenix, :json_library, Poison

  (phoenix 1.5.7) lib/phoenix.ex:38: Phoenix.start/2
  (kernel 6.5.2) application_master.erl:277: :application_master.start_it_old/4

==> web_interface
Compiling 17 files (.ex)

== Compilation error in file lib/web_interface_web/endpoint.ex ==
** (ArgumentError) invalid :json_decoder option. The module Poison is not loaded and could not be found
    (plug 1.10.3) lib/plug/parsers/json.ex:44: Plug.Parsers.JSON.validate_decoder!/1
    (plug 1.10.3) lib/plug/parsers/json.ex:31: Plug.Parsers.JSON.init/1
    (plug 1.10.3) lib/plug/parsers.ex:253: anonymous fn/3 in Plug.Parsers.convert_parsers/2
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.10.3) lib/plug/parsers.ex:234: Plug.Parsers.convert_parsers/2
    (plug 1.10.3) lib/plug/parsers.ex:230: Plug.Parsers.init/1
    (plug 1.10.3) lib/plug/builder.ex:304: Plug.Builder.init_module_plug/4
    (plug 1.10.3) lib/plug/builder.ex:288: anonymous fn/5 in Plug.Builder.compile/3
```

I need to fix it so when I merge to master I can get the pipeline passing.

**Comment by Fl4m3Ph03n1x** [comment]
The reason the command fails is because my phoenix app is not aware it is inside an umbrella app:

https://elixirforum.com/t/mix-test-failing-for-umbrella-project-due-to-phoenix-liveview/39612/3

To fix this I must re-create the app with the right context, meaning I must tell my phoenix app it is inside an umbrella app.
This is proving more difficult than I originally thought, as I cannot make it work by default:

https://elixirforum.com/t/cannot-create-phoenix-app-inside-umbrella-project/39970

**Comment by Fl4m3Ph03n1x** [comment]
Turns out it was a new line issue. Since I am in Windows, the format is CRLF, while the code was expected LF. A few things that can help fix this:
 - use .gitattributes file and set eol to LF
 - set vscode settings
 - use mix format (which automatically does this).

I did the first 2 points, but until I fix rop I cannot do the third one.

**Comment by Fl4m3Ph03n1x** [comment]
Fixed, I just had to REMAKE the full thing ... what a ride!
